/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: main-20240823173931
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtsCollectionFilter
 */
export interface DtsCollectionFilter {
    /**
     * 
     * @type {string}
     * @memberof DtsCollectionFilter
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DtsCollectionFilter
     */
    showDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DtsCollectionFilter
     */
    searchAttribute?: string;
}

/**
 * Check if a given object implements the DtsCollectionFilter interface.
 */
export function instanceOfDtsCollectionFilter(value: object): boolean {
    return true;
}

export function DtsCollectionFilterFromJSON(json: any): DtsCollectionFilter {
    return DtsCollectionFilterFromJSONTyped(json, false);
}

export function DtsCollectionFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtsCollectionFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'showDeleted': json['showDeleted'] == null ? undefined : json['showDeleted'],
        'searchAttribute': json['searchAttribute'] == null ? undefined : json['searchAttribute'],
    };
}

export function DtsCollectionFilterToJSON(value?: DtsCollectionFilter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'showDeleted': value['showDeleted'],
        'searchAttribute': value['searchAttribute'],
    };
}

