/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: main-20240823173931
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtsCollectionVO
 */
export interface DtsCollectionVO {
    /**
     * 
     * @type {string}
     * @memberof DtsCollectionVO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DtsCollectionVO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DtsCollectionVO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DtsCollectionVO
     */
    template?: string;
    /**
     * 
     * @type {string}
     * @memberof DtsCollectionVO
     */
    templateRepo?: string;
    /**
     * 
     * @type {Date}
     * @memberof DtsCollectionVO
     */
    createdTs?: Date;
}

/**
 * Check if a given object implements the DtsCollectionVO interface.
 */
export function instanceOfDtsCollectionVO(value: object): boolean {
    return true;
}

export function DtsCollectionVOFromJSON(json: any): DtsCollectionVO {
    return DtsCollectionVOFromJSONTyped(json, false);
}

export function DtsCollectionVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtsCollectionVO {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'template': json['template'] == null ? undefined : json['template'],
        'templateRepo': json['templateRepo'] == null ? undefined : json['templateRepo'],
        'createdTs': json['createdTs'] == null ? undefined : (new Date(json['createdTs'])),
    };
}

export function DtsCollectionVOToJSON(value?: DtsCollectionVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'template': value['template'],
        'templateRepo': value['templateRepo'],
        'createdTs': value['createdTs'] == null ? undefined : ((value['createdTs']).toISOString()),
    };
}

